#S3
aws:
  s3:
    host.url: http://localhost:9000/minio/
    access.key: negativ529021
    secret.key: granit1506
    bucket: rest-feign/

#datasource:
datasource:
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:postgresql://localhost:5432/rest_feign
  driver-class-name: org.postgresql.Driver
  username: postgres
  password: granit1506
  hikari:
    connectionTimeout: 30000
    maximumPoolSize: 10
    minimumIdle: 2
    transactionIsolation: TRANSACTION_READ_COMMITTED
    connectionTestQuery: SELECT version()

# hibernate
jpa:
  database: PostgreSQL
  hibernate:
    ddl-auto: none
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
